---

- name: RSYSLOG | Ensure rsyslog group
  group:
    name: "{{ rsyslog_group }}"
    system: true

- name: RSYSLOG | Ensure rsyslog user
  user:
    name: "{{ rsyslog_user }}"
    group: "{{ rsyslog_group }}"
    groups: systemd-journal
    shell: /bin/false
    create_home: false
    system: true

- name: RSYSLOG | Ensure rsyslog dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rsyslog_user }}"
    group: "{{ rsyslog_group }}"
  loop:
    - "{{ rsyslog_work_directory }}"
    - "{{ rsyslog_include_config_matcher | dirname }}"
    - "{{ rsyslog_logs_directory }}"

- name: RSYSLOG | Install required libs
  apt:
    name: "{{ rsyslog_required_libs }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: rsyslog_required_libs_installed
  until: rsyslog_required_libs_installed is succeeded
  notify: restart rsyslog

- name: RSYSLOG | Install rsyslog core package
  apt:
    name: "{{ rsyslog_package }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: rsyslog_core_package_installed
  until: rsyslog_core_package_installed is succeeded
  notify: restart rsyslog

- name: RSYSLOG | Install rsyslog feature packages
  apt:
    name: "{{ rsyslog_feature_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: rsyslog_feature_packages_installed
  until: rsyslog_feature_packages_installed is succeeded
  notify: restart rsyslog

- name: RSYSLOG | Copy include config templates
  template:
    src: "{{ item }}"
    dest: "{{ rsyslog_include_config_path }}/{{ item | basename }}"
    owner: "{{ rsyslog_user }}"
    group: "{{ rsyslog_group }}"
  with_fileglob:
    - "{{ rsyslog_included_config_template_path }}/*"
  notify: restart rsyslog
