---
- name: Consul | Gather  OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  ignore_errors: true
  tags:
    - install

- name: RSYSLOG | Install
  import_tasks: install.yml
  tags:
    - rsyslog-install

- name: RSYSLOG | Config
  import_tasks: config.yml
  tags:
    - rsyslog-config

- name: RSYSLOG | Service
  import_tasks: service.yml
  tags:
    - rsyslog-service
