# Molecule managed
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
{% if item.image == 'debian:jessie-slim' %}
RUN if [ $(command -v apt-get) ]; then \
      apt-get update \
      && apt-get install -y --force-yes python systemd systemd-sysv sudo bash ca-certificates iproute2 \
      && apt-get clean; \
    fi
{% else %}
RUN if [ $(command -v apt-get) ]; then \
      apt-get update \
      && apt-get install -y python systemd systemd-sysv sudo bash ca-certificates iproute2 \
      && apt-get clean; \
    fi
{% endif %}
