# Molecule managed
{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then \
      apt-get update \
      && apt-get install -y python systemd systemd-sysv sudo bash ca-certificates iproute2 \
      && apt-get clean; \
    fi
