---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
      ansible-lint .
platforms:
  - name: rsyslog-test
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/sys/fs/fuse/connections:/sys/fs/fuse/connections:ro'
    groups:
      - rsyslog
    command: '/lib/systemd/systemd'
    tmpfs:
      - '/run'
      - '/run/lock'
    devices:
      - '/dev/fuse:/dev/fuse'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: ansible
